pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'win64'
    targetPath: '$(system.defaultworkingdirectory)/OpenDiablo2/bin/$(buildPlatform)/$(buildConfiguration)'
